### ISSUE TITLE
Issues with version 2.5.1

### ISSUE THREAD

**Issue by simtrax** [tanthammar/laravel-rules#1]
Hi!

I'm trying to use the package to validate PersonOrOrgNummer.
Unfortunately in version 2.5.1 when you migrated to TantHammar\LaravelExtras it seems that the composer.json file is still refering to "tanthammar/laravel-extras": "dev-master".
I guess that's your local version.

So installing version 2.5.1 is not possible it seems. It falls back to version 2.5 I guess.
And in that version I get the following error:
`Class "TantHammar\LaravelExtras\LaravelExtrasHelpers" not found`.

Kind regards,
Simon :)

**Comment by tanthammar** [comment]
Tnx for reporting. Yes it might be my local installation ... will look into it asap.

**Comment by tanthammar** [comment]
@simtrax 
Ber tusen om ursäkt, helt glömt...
Kan du verifiera att v 2.6 funkar?

**Comment by simtrax** [comment]
Jag provade ta bort paketet och installera det igen för att vara säker på att v 2.6 installerades.

Det ser ut som att det räcker med att du tar bort `tanthammar/laravel-extras` från composer.json.

Får detta meddelandet fortfarande:
```
Problem 1
    - Root composer.json requires tanthammar/laravel-rules ^2.6 -> satisfiable by tanthammar/laravel-rules[2.6.0].
    - tanthammar/laravel-rules 2.6.0 requires tanthammar/laravel-extras dev-master -> could not be found in any version, there may be a typo in the package name.
```

**Comment by tanthammar** [comment]
@simtrax 
LOL, det tog en stund innan jag insåg (1), att jag inte lagt upp pkg på Packagist och (2), att aldrig använda "master" som branch namn. Har mina andra som "main"... Master krockar tydligen med v1.x taggar.
Men nu funkar det väl?
Förlåt för besväret ...

**Comment by simtrax** [comment]
Det ser ut att fungera utmärkt! 
Tack så mycket :)

**Comment by tanthammar** [comment]
Tack själv för tålamodet.
